name: Deploy to GH Pages
on: [push]

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Jekyll Actions
        uses: helaili/jekyll-action@2.0.0
        env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}